name: Deploy to DigitalOcean
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build

    - name: Deploy to server
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        
        script: |
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html
